### ISSUE TITLE
Aim2 - Simulations and sensors noise - sensors number plot

### ISSUE THREAD

**Issue by contsili** [contsili/master-thesis#2]
**Description**

Run simulations and create a sensors noise - sensors number plot and color code with σ_opm/σ_squid > 1 ⇒ blue (SQUID wins), σ_opm/σ_squid < 1 ⇒ red (OPM wins)

**Simulation characteristics**

```
sensor_noise_SQUID = 1 * 10^-10; % I picked it randomly

sensor_noise_OPM = [0.1 * 10^-10, 1 * 10^-10, 10 * 10^-10, 100 * 10^-10];
sensor_number_OPM = 201:20:301;

k = 1:12 % 12 iterations of dipole fits
```

**Results**

https://github.com/contsili/master-thesis/blob/main/simulations/results/aim2/sensor_noise-sensor_number.jpg

1. For high sensor noise, SQUID always wins. This is logical as `sensor_noise_SQUID = 1 * 10^-10` while `sensor_noise_OPM_max = 100 * 10^-10.
`
2. For `sensor_noise_SQUID = sensor_noise_OPM = 1 * 10^-10`, SQUID wins when OPM has the maximum of sensors. This is not logical and should not happen. 

**Questions**

1. For the 2nd result: Why does that happen? Do I need to run more iterations of dipole fits (here I ran 12 iterations)? Do I have a mistake in my code or in the ideas that my code is based on (for example, the way I do the OPM sensor selection, this relates to issue #1)?
2. What is a typical sensor noise level for a CTF275 system that would help us make the simulations more realistic? In my code, I used a random value, which is `sensor_noise_SQUID = 1 * 10^-10`. An idea I have to solve this issue is by running an experiment in the CTF275 system. Then the sensor noise will be equal to the topography of the raw signal (=Vdata) minus the modelled topography (Vmodel). Any thoughts?

**Comment by contsili** [comment]
### Notes from meeting - 24/10/2023

Together with @robertoostenveld we discussed about:

**General Suggestion for the sensors noise - sensors number plot:**

- [ ] Make the color coding more continuous using MATLAB colormaps and apply log transformation to make it symmetric (0 at the center, ranging from -inf to +inf).

**Answer to Question 1**

- [ ] Propose simplifying the plot by making it 2D (e.g, sigma - sensor nr. In general, I expect the more the sensor nr the less the sigma. But what is the relationship: linear, 1/r, 1/r^2  etc?). After doing that we will see if something is wrong and if we need to look at the code in more detail.

**Suggestions by Robert to make the code faster**

We looked at the `forward_model.m` with Robert and he suggested to:
- [ ] Improve efficiency by reducing time samples in the dipole fit. For example, now I have: 
```
data.time=linspace(0.01,1,100);
data.avg = repmat(leadfield1,1,100);
```
but I should have:
```
data.time=linspace(0.01,1,1);
data.avg = repmat(leadfield1,1,1);
```

- [ ] Avoid using the third loop and implement dipole iteration for a static dipole in different time slices of the `ft_dipolefit`. We made changes to the code with Robert and I will commit them soon. TODO: Export a 100x3 matrix for dip_location_OPM(k,:) = dip.dip.pos.

- [ ] Use Singular Value Decomposition (SVD) for computing the standard deviation (sigma), where sigma is the product of the trace of the covariance matrix, representing the elongation of the ellipsoid. Note that if sigmas in x,y and z direction were independent, I would have a spherical pattern of dipole fits and then I could use the formula from the Vrba (2000) paper:          `sigma_location_OPM(i,j) = sqrt((std(dip_location_OPM(:,1))^2 + std(dip_location_OPM(:,2))^2 + std(dip_location_OPM(:,3))^2)  / 3 );`.


**Answer to Question 2**

- [ ] It **is not** a problem if we do not determine exactly the SQUID sensor noise **if we only care about the OPM characteristics**. In other words, the colorbar is going to vary the same way whatever the log(σ_SQUID) is, because it depends only on log(σ_OPM) (If σ_SQUID high then log(σ_OPM)-log(σ_SQUID)=[-0.1,1.9], If σ_SQUID low then log(σ_OPM)-log(σ_SQUID)=[-1,1] but the color is varying the same way (=with the same gradient)). Run simulation with different σ_SQUID to see that. 

- [ ] It **is** a problem if we do not determine exactly the SQUID sensor noise, if we zoom-in a bit more in the analysis and try to **compare OPM and SQUID**.

- [ ] Yes, SQUID noise can be calculated by taking the residue: Residue = Vdata-Vmodel, (this is different for every channel). We want one number for all channels and this is the residual variance which is Tesla^2. Alternatives to residual variance are the  goodness of fit or the relative difference metric (rdm).


- **Residual variance** does _**not** depend on where and how strong the dipole is_, but **relative residual variance** depends on _where and how strong the dipole is_ (because the signal increases on where the dipole is, but the absolute noise is everywhere the same)

- **SNR** is not important for my research question, since it is _**not** dependent on the nr of channels_, because the noise and the signal is the same as many channels as we have.

**Comment by contsili** [comment]
With the commit 1659703, I made changes to the `forward_model.m`. After I ran again some simulations.

**Simulation characteristics**

```
%% SQUID
sensor_noise_SQUID = 1 * 10^-10; % I picked it randomly

k = 1:20 % 20 iterations of dipole fits for SQUID

%% OPM
sensor_noise_OPM = [0.1 * 10^-10, 1 * 10^-10, 10 * 10^-10, 100 * 10^-10];
sensor_number_OPM = 201:20:301;

% IMPROVEMENT: I used the trick suggested by Robert about implementing dipole iteration for a static dipole in different time slices of the ft_dipolefit. That way I did 100 dipole iterations.
data.time=linspace(0.01,1,100); % 100 dipole fit iterations
data.avg = repmat(leadfield1,1,100)+ sensor_noise_OPM(i) * randn(1, 100);
```

**Results**
https://github.com/contsili/master-thesis/blob/main/simulations/results/aim2/24102023_sensor_noise-sensor_number.jpg

Answer to Question 1 posted earlier in this issue: _Do I need to run more iterations of dipole fits (here I ran 12 iterations)?_ It seems like **yes**, since now my results are more logical.

**Comment by contsili** [comment]
### Notes from meeting - 31/10/2023

- [ ] This plot: https://github.com/contsili/master-thesis/blob/main/simulations/results/aim2/24102023_sensor_noise-sensor_number.jpg is at the saturation zone. I need to do simulations with lower number of sensors to find the "green" line. 
- [ ] Do also the 2D plots and add them as different panels in 1 big plot. In general, I know that more sensors leads to lower sigma (dipole fit uncertainty), but it is interesting to find the analytical mathematical relation. Fit the 2D plots and see what is the analytical mathematical relation between sigma and number of sensors (i.e., is it sigma = 1/n, or 1/n2 or is it linear?). Search also for papers that prove this relation with pure maths (the maths behind it relate to the error propagation).
- [ ] Do all the simulations with the `mesh_sphere()` function. I expect the results in the 2D and 3D plots to be more smooth.

**Suggested papers**

- [ ] Fuchs, M., Wagner, M., & Kastner, J. (2004). Confidence limits of dipole source reconstruction results. CLINICAL NEUROPHYSIOLOGY, 115(6), 1442–1451. https://www.sciencedirect.com/science/article/pii/S138824570400032X?via%3Dihub

- [ ] Iivanainen, J., Stenroos, M., & Parkkonen, L. (2017). Measuring MEG closer to the brain: Performance of on-scalp sensor arrays. NeuroImage, 147, 542–553. 
https://www.zotero.org/groups/5184453/opm-ru/collections/A98VKURQ/items/IVW2LE79/attachment/W6AMDJHX/reader

**Comment by contsili** [comment]
With the commit #1659703, I made changes to `forward_model.m`. In short, 
1. I did simulations with lower number of sensors to find the green line. 
2. I did the 2D plots (dipole fit uncertainty - OPM sensor number plot, for different OPM sensor noise) and added them as different panels in 1 big plot. I fitted one quadratic and one cubic line
3. My research question is focused on the green line, so when `sigma_location_relative(i,j) = 1`. For this reason, I kept the sigma_location_relative values in the range [0,2]. Values in the range [2,inf], I force them to be equal to NaN (white squares in the 3D colored plot).

**Simulation characteristics**

```
%% SQUID
sensor_noise_SQUID = 1 * 10^-10; % I picked it randomly

k = 1:20 % 20 iterations of dipole fits for SQUID

%% OPM
sensor_noise_OPM = [5 * 10^-10, 7 * 10^-10, 9 * 10^-10, 10 * 10^-10, 11 * 10^-10, 13 * 10^-10, 16 * 10^-10,  20 * 10^-10, 25 * 10^-10];
sensor_number_OPM = 21:15:201;

100 iterations of dipole fits for OPM
```

**Results**

Quadratic fit: https://github.com/contsili/master-thesis/blob/main/simulations/results/aim2/03112023_sensor_noise-sensor_number_(quadratic-fit).jpg
Cubic fit: https://github.com/contsili/master-thesis/blob/main/simulations/results/aim2/03112023_sensor_noise-sensor_number_(cubic-fit).jpg

**Comment by contsili** [comment]
### Notes from meeting - 31/10/2023
                                                                                                                                                                                     -  Could you Could you repeat why we choose the dipole fit (or moment) uncertainty (σ) and not the SNR as a metric for comparing OPM and SQUIDs. What I understand is that SNR is related to each sensor (but why then SNR = 1/sqrt(number of sensors) ???), while σ is related to the system as a whole. Also, after one of our previous meetings I wrote down that: ''SNR is not important for my research question, since it is not dependent on the number of channels, because the noise and the signal is the same as many channels as we have.'' Is that correct?                                                                                                        

I tried to write more clearly the mathematical formulas we discussed today (see attached figure). Is that correct?

As a follow-up to my simulations: As far as I understand, my next step is to use the phantom data to find the noise of the SQUIDs (by specifying cfg.model = 'regional':wink:. After that, I have size(source.dip.mom) = 3 x 600. I will then compare the dipole moment that I expect to see for each time point (based on the max dipole moment and the 7Hz sinusoidal time course I know a priori to my experiment) with the one I fitted. Then I will use the noise of the SQUIDs, in my simulations. My simulations now will be based on the dipole moment uncertainty and not the dipole fit uncertainty. However, I expect that dipole moment uncertainty and the dipole fit uncertainty should find the same number of OPM sensors needed to answer my research question.

**Comment by robertoostenveld** [comment]
> Could you repeat why we choose the dipole fit (or moment) uncertainty (σ) and not the SNR as a metric ...

The SNR is not _one_ metric, but it is a vector of the same length as the number of sensors. Considering your phantom recording: some sensors (on the left and right) will have a high SNR, whereas others along the midline will have a low SNR (or even zero). The noise of the dipole moment (or the SNR of the dipole moment) _is_ a single metric. 

The SNR for the dipole moment scales with the number of sensors (more sensors, less noise). The SNR for a single sensor does not change if I add other sensors. 

Your notes are correct, except that the final statement should read: _"So based on eq 4 we can either derive the number of sensors (the number of channels in the leadfield vector) when we assume a certain noise for the OPMs, or we can derive the required noise level for the OPMs, when we assume a certain number of sensors (the number of channels in the leadfield vector)."_ 

Both terms in the denominator of eq 4 are known, both terms in the numerator are unknown. So if you fix one of the unknowns, you can compute the other.

**Comment by contsili** [comment]
Thank you, Robert! The difference between the SNR _for the dipole moment_ and the SNR _for a single sensor_ is clear to me now.

Could you also express your thoughts on the follow-up to my simulations, that I suggested in the previous comment?

In short, the follow-up to my simulations will be to find the number of OPM sensors needed to answer my research question (i.e., how many OPM-MEG sensors do we need to outperform the existing 275-channel SQUID-MEG system from CTF?) with 3 different ways:
1.  dipole moment uncertainty 
2.  dipole fit uncertainty
3.  analytically using the eq. 4

All three ways should give roughly the same number of OPM sensors. Once this happens, I can use the 3rd analytical way from now on because it is computationally faster and accurate (i.e., it does not depend on the Monte-Carlo simulations).

**Comment by robertoostenveld** [comment]
> Could you also express your thoughts on the follow-up to my simulations, that I suggested in the previous comment?


Looks good to me!

**Comment by contsili** [comment]
I tried to answer my research question analytically using the eq. 4. The MATLAB code I used:

```
%% Analytical solution of sensor number when we assume a certain noise for the OPMs


sensor_noise_OPM = 20 * 10^-15; % Fieldline paper: the remaining average noise floor (after SSP, look figure 5B) is 20 ± 5 fT/Hz^1/2.

% SQUID
sensor_noise_SQUID =  5 * 10^-15; % In intranet it says: The noise levels of MEG sensors should be below 10 fT, usually around 4-7fT. (https://intranet.donders.ru.nl/index.php?id=meg-lab-procedure-noiserecording&no_cache=1&sword_list%5B%5D=lab)


headmodel = ni2_headmodel('type', 'spherical', 'nshell', 1); 
sensors = ni2_sensors('type', 'ctf275');  

dippar = [0 0 6 1 0 0];

leadfield = ni2_leadfield(sensors, headmodel, dippar, sensor_noise_SQUID);

leadfield_pinv_SQUID = pinv(leadfield);

% OPM
leadfield_pinv_OPM = leadfield_pinv_SQUID * sensor_noise_SQUID / sensor_noise_OPM;
sensor_number_OPM = length(leadfield_pinv_OPM);
```

**Problem**
 The equation `leadfield_pinv_OPM = leadfield_pinv_SQUID * sensor_noise_SQUID / sensor_noise_OPM;` is intended to give a matrix with a reduced length (i.e., less OPM sensors needed), as sensor_noise_OPM decreases. However, it consistently yields a matrix with the same length as leadfield_pinv_SQUID (i.e, it is always equal to 273 which are the MEG channels of the ctf275 system) which makes sense based on the equation I presented above. Any thoughts?

**Comment by robertoostenveld** [comment]
what do you expect the dimensions of each of the matrices to be? The sensor noise for both systems is a scalar, hence `sensor_noise_SQUID / sensor_noise_OPM` is also a scalar. You don't expect the leadfields (or the inverse leadfields) to be a scaled version of each other, right? Although that would be _a_ solution, it is not the one you are looking for. What you want to equate is the variance of the estimated dipole strength for both systems. So please start with the equation for the forward solution and solve that, given the known noise covariance matrices (an IID matrix, i.e. diagonal matrix with on the diagonal the sensor noise squared).

**Comment by contsili** [comment]
### Sanity checks of eq. 4
I moved on with eq. 4 and I performed some _sanity checks._

**1. High source depth, more sensors needed: Proven**
![depth](https://github.com/contsili/master-thesis/assets/105793148/2874f13a-85a2-4072-9b93-f473e3ee6ef0)

**2. Figure 2E, from https://www.sciencedirect.com/science/article/pii/S1053811921003025?via%3Dihub: Not proven**
![L-sensor_number_OPM](https://github.com/contsili/master-thesis/assets/105793148/bd9413db-7c22-4b5b-b1f3-c1fb343cdeb1)

**3. sensor_noise_OPM ~ sqrt(sensor_number_OPM) (5): Not proven**
Proof of (5):  ||pinv(L_SQUID)|| and N_SQUID are constants. Then, from eq. 4: N_OPM~||L_OPM||~ sqrt(sensor_number_OPM)

The relation I find looks more like sensor_noise_OPM ~ (sensor_number_OPM)^2. For example: see the blue figure in "1. High source depth, more sensors needed: Proven"

**4. SQUIDs vs SQUIDs: Proven**
The idea we discussed with Robert at the meeting was to create an OPM system that has the same sensor noise,  the same distance from the scalp  and the same sensor topography as the SQUIDs (Note: from the SQUID I would only keep the 275 magnetometers (not the gradiometers). That way, we could check if my analytical formula gives the expected result ` sensor_number_OPM = 275` in order for the two systems to have the same dipole moment uncertainty.

I thought I could keep it more simple and compare a SQUID system with a SQUID system that has unknown number of sensors.

For `sensor_noise_SQUID_unknown = sensor_noise_SQUID = 1 * 10^-15; : 
`



The code I used for 1., 2., 3.:
```sensor_noise_OPM = linspace(0.01, 10, 20)*10^-10;

leadfield_OPM_eq4 = zeros(1,length(sensor_noise_OPM));

% Loop over different OPM sensor noise levels
for i = 1:length(sensor_noise_OPM)

    % Set a fixed SQUID sensor noise level based on lab information
    sensor_noise_SQUID =  1e-10; % NOTE: ONLY in **1. High source depth, more sensors needed: Proven** I used sensor_noise_SQUID =  7e-10; (this was done unintentionally)
 

    headmodel = ni2_headmodel('type', 'spherical', 'nshell', 1); 
    sensors = ni2_sensors('type', 'ctf275');      
    dippar1 = [0 0 9 1 0 0];  
    leadfield = ni2_leadfield(sensors, headmodel, dippar1, sensor_noise_SQUID);


    % I want the dipole moment uncertainty of the OPM to be equal to the one from the SQUID. I compute that analytically using eq. (4) from https://github.com/contsili/master-thesis/issues/2#issuecomment-1799608261
    leadfield_OPM_eq4(i) = norm(leadfield) * sensor_noise_OPM(i) / sensor_noise_SQUID;
    
    % Solve the forward model for a radial OPM system
    headmodel = ni2_headmodel('type', 'spherical', 'nshell', 1); 
    sensors = ni2_sensors('type', 'opm_radial');    
    dippar2 = dippar1;     
    leadfield1 = ni2_leadfield(sensors, headmodel, dippar2, sensor_noise_OPM(i));
    leadfield_OPM_forward = norm(leadfield1);

    % Find the number of OPM sensors by weighting the norm of
    % leadfield from eq. 4 with the norm of the leadfield by forward model for a radial OPM system    
    sensor_number_OPM(i) = length(leadfield1) * leadfield_OPM_eq4(i) / leadfield_OPM_forward

    %% (Optional) The following code snippet was an attempt to calculate sensor number differently, but it does not give the expected results:
    % sensitivity = mean(leadfield1(1:301));
    % sensor_number_OPM(i) = (leadfield_OPM(i) / sensitivity)^2
    
end

Plot the results
figure;
scatter(sensor_number_OPM, sensor_noise_OPM) % I expect sensor_noise_OPM ~ sqrt(sensor_number_OPM) but this does not happen. Why?
xlabel('OPM sensor number')
ylabel('OPM sensor noise')

figure;
scatter(sensor_number_OPM, leadfield_OPM_eq4) % This should be the same as the fig. 2E from the paper https://doi.org/10.1016/j.neuroimage.2021.118025. But it is not the same. Why?
xlabel('OPM sensor number')
ylabel('||L||')
````

The code for 4.:
`````
sensor_noise_SQUID_unknown = 1 * 10^-15;

sensor_noise_SQUID =  1 * 10^-15; 


headmodel = ni2_headmodel('type', 'spherical', 'nshell', 1); 
sensors = ni2_sensors('type', 'ctf275');  
dippar = [0 0 6 1 0 0];
leadfield = ni2_leadfield(sensors, headmodel, dippar, sensor_noise_SQUID);

% I want the dipole moment uncertainty of the OPM to be equal to the one from the SQUID. I compute that analytically using eq. (4) from https://github.com/contsili/master-thesis/issues/2#issuecomment-1799608261    
leadfield_SQUID = norm(leadfield) * sensor_noise_SQUID_unknown / sensor_noise_SQUID;

% Compute 50 instances of the number of sensors for the SQUID system with
% an unknown number of sensors and in the average:
for i=1:50 

    % Solve the forward model for a SQUID system with an unknown number of
    % sensors
    headmodel = ni2_headmodel('type', 'spherical', 'nshell', 1); 
    sensors = ni2_sensors('type', 'ctf275');      
    dippar = [0 0 6 1 0 0];   
    leadfield1 = ni2_leadfield(sensors, headmodel, dippar, sensor_noise_SQUID_unknown);
    leadfield_SQUID_default_mean(i) = norm(leadfield1);
    
    % Find the number of OPM sensors by weighting the norm of
    % leadfield from eq. 4 with the norm of the leadfield by forward model for a radial OPM system    
    sensor_number_SQUID(i) = length(leadfield1) * leadfield_SQUID / leadfield_SQUID_default_mean(i)
end

sensor_number_SQUID_average = mean(sensor_number_SQUID)
`````

### TODO
5. SQUID vs OPM that is like a SQUID (see "4. SQUID vs SQUID" for more information)
6. Do not force eq. 4 equal to 1 and find how the quotient on the left side of the equation varies based on the sensor_number_OPM (my thought it should be propotional to 1/sqrt(sensor_number_OPM), and the sensor_noise_OPM

### Questions
Can you help me understand why 2. and 3. are different from the results I expect?

**Comment by robertoostenveld** [comment]
Q a) In your figure 2 you have "noise" on the line, which presumably is because you are switching between different spatial arrangements of the sensors, where the sensors have slightly different coverage and leadfields. You can deduce that it is linear, if you do the thought experiment of putting N sensors all on the same place. Of course that results in crappy spatial coverage, and you would not be able to fit any dipole with that, but the leadfield becomes a trivial replication of the same value for each channel. 

Q b) The L2 norm of a vector is the same as its length, which is what you would compute with Pythagoras' rule. So  indeed ` || l || = sqrt(sum( l_i ^2)`, but I would not say "corrected", as I don't see anything that is incorrect.

**Comment by contsili** [comment]
Today after a quick meeting with Robert we discussed:

> In your figure 2 you have "noise" on the line, which presumably is because you are switching between different spatial arrangements of the sensors, where the sensors have slightly different coverage and leadfields

In my simulations I am keeping the same spatial arrangements of the OPM sensors (301 sensors on a cosahedron), so this is not a problem

>You can deduce that it is linear

He means ||L|| ~ sqrt(number of sensors) (this is not linear), while ||L||^2 ~ number of sensors (this is linear)

Suggestions to correct 2. and 3.:
a. Avoid using randn, 
b. In eq. (4) use ||pinv(L)|| (not ||L||) - In that case do not trust the Brooke's paper



### DRAFT

GENERAL ADVICE: Change the y, x acis (IV is the noise, DV is the number) - but in general we want DV to be the σ/σ (this is my research question!!! - i have to keep my focus on that)

SOLUTION TO OILD SIMULATION: SQUIDvsSQUID good but rephrase the Q (it depends on The number of SQUID sensors since I do not vary the spatial topography)

NEW: Do σ/σ without fixing it to 1
NEW: Cortical sheet: σOPM 275, σSQUID 275, sqrt(relative)*275 (also for bti helmet)


(Firldlinebetahelmet)

(Do my analysis from the beginning - plot the sensors and the dipole - but i have done that)
